POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "password",
  "confirm_password": "password"
}

###
POST http://localhost:3000/question
Content-Type: application/json

{
  "title":  "some title",
  "content":  "some content",
  "tags": ["tag1", "tag2"]
}

###
GET http://localhost:3000/questions
Accept: application/json

###
GET http://localhost:3000/questions/1
Accept: application/json

###
GET http://localhost:3000/blargh
Accept: application/json
